src/BlogSharp.Web/Controllers/PublicacoesController.cs
using AutoMapper;
using BlogSharp.Data.Data;
using BlogSharp.Data.Entities;
using BlogSharp.Data.Interfaces;
using BlogSharp.Data.Models;
using BlogSharp.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BlogSharp.Web.Controllers
{
    public class PublicacoesController : Controller
    {
        private readonly ApiDbContext _context;
        private readonly IMapper _mapper;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IAspnetUser _aspnetUser;

        public PublicacoesController(
            ApiDbContext context, IMapper mapper, IWebHostEnvironment webHostEnvironment, IAspnetUser aspnetUser)
        {
            _context = context;
            _mapper = mapper;
            _webHostEnvironment = webHostEnvironment;
            _aspnetUser = aspnetUser;
        }

        public async Task<IActionResult> Index(bool filtroPorUsuario = false)
        {
            var userId = _aspnetUser.GetUserId();
            var publicacoes = await _context.Publicacoes.Include(p => p.Autor).OrderByDescending(p => p.DataPublicacao).Where(p => !filtroPorUsuario || p.AutorId == Guid.Parse(userId)).ToListAsync();

            var resultado = _mapper.Map<List<PublicacaoResponseModel>>(publicacoes);

            ViewBag.FiltroPorUsuario = filtroPorUsuario;

            return View(resultado);
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(PublicacaoModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            if (model.ImagemFile != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "imagens");
                string uniqueFileName = Guid.NewGuid().ToString() + "_" + model.ImagemFile.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await model.ImagemFile.CopyToAsync(fileStream);
                }

                model.Imagem = uniqueFileName;
            }

            var publicacao = _mapper.Map<Publicacao>(model);

            var userId = _aspnetUser.GetUserId();

            publicacao.CriarPublicacao(Guid.Parse(userId));

            _context.Publicacoes.Add(publicacao);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public async Task<IActionResult> Edit(Guid id)
        {
            var post = await _context.Publicacoes.FirstOrDefaultAsync(p => p.Id == id);
            var resultado = _mapper.Map<PublicacaoModel>(post);

            return View(resultado);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(PublicacaoModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            if (model.ImagemFile != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "imagens");
                string uniqueFileName = Guid.NewGuid().ToString() + "_" + model.ImagemFile.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await model.ImagemFile.CopyToAsync(fileStream);
                }

                model.Imagem = uniqueFileName;
            }
            else
            {
                model.Imagem = model.ImagemAtual;
            }

            var publicacao = _mapper.Map<Publicacao>(model);

            var publicacaoDb = await _context.Publicacoes.FirstOrDefaultAsync(p => p.Id == model.Id);
            publicacaoDb.Atualizar(publicacao);

            _context.Publicacoes.Update(publicacaoDb);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Excluir(Guid publicacaoId)
        {
            if (publicacaoId == null)
            {
                ModelState.AddModelError("", "ID da publicação inválido.");
                return RedirectToAction(nameof(Index));
            }

            var publicacao = await _context.Publicacoes.FirstOrDefaultAsync(p => p.Id == publicacaoId);
            if (publicacao == null)
            {
                return NotFound();
            }

            _context.Publicacoes.Remove(publicacao);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var post = await _context.Publicacoes
                                            .Include(p => p.Autor)
                                            .Include(p => p.Comentarios.OrderByDescending(x => x.DataPublicacao))
                                                .ThenInclude(p => p.Autor)
                                            .FirstOrDefaultAsync(p => p.Id == id);

            var publicacao = _mapper.Map<PublicacaoResponseModel>(post);

            var viewModel = new PublicacaoComentarioViewModel()
            {
                Publicacao = publicacao,
                Comentario = new ComentarioModel(),
                PublicacaoId = id
            };

            var usuarioLogado = false;
            var usuarioAdmin = false;

            var userId = _aspnetUser.GetUserId();

            if (string.IsNullOrEmpty(userId))
                return View(viewModel);

            var usuario = await _context.Usuarios.FirstOrDefaultAsync(p => p.Id == Guid.Parse(userId));

            if (usuario != null && usuario.Administrador)
                usuarioAdmin = true;

            ViewBag.UsuarioId = Guid.Parse(userId);
            ViewBag.UsuarioAdmin = usuarioAdmin;

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> AdicionarComentario(PublicacaoComentarioViewModel model)
        {
            var userId = _aspnetUser.GetUserId();

            var comentario = new Comentario(model.Comentario.Descricao, Guid.Parse(userId), model.PublicacaoId);

            _context.Comentarios.Add(comentario);
            await _context.SaveChangesAsync();

            return RedirectToAction("Details", new { id = model.PublicacaoId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> EditarComentario(Guid comentarioId, Guid publicacaoId, string descricao)
        {
            var comentario = await _context.Comentarios.FirstOrDefaultAsync(p => p.Id == comentarioId);

            if (comentario == null)
            {
                return NotFound();
            }

            comentario.Atualizar(descricao);

            _context.Comentarios.Update(comentario);
            await _context.SaveChangesAsync();

            return RedirectToAction("Details", new { id = publicacaoId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> ExcluirComentario(Guid comentarioId, Guid publicacaoId)
        {
            if (comentarioId == null)
            {
                ModelState.AddModelError("", "ID do comentário inválido.");
                return RedirectToAction("Details", new { id = publicacaoId });
            }

            var comentario = await _context.Comentarios.FirstOrDefaultAsync(p => p.Id == comentarioId);
            if (comentario == null)
            {
                return NotFound();
            }

            _context.Comentarios.Remove(comentario);
            await _context.SaveChangesAsync();

            return RedirectToAction("Details", new { id = publicacaoId });
        }
    }
}

src/BlogSharp.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogSharp.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogSharp.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Publicacoes" asp-action="Index">BlogSharp.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Publicacoes" asp-action="Index" asp-route-filtroPorUsuario="true">Minhas Publicações</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Publicacoes" asp-action="Create">Nova Publicação</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!--
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BlogSharp.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>